### ISSUE TITLE
token_type pop conflicts with definition in draft-ietf-oauth-signed-http-request

### ISSUE THREAD

**Issue by selfissued** [webhamster/draft-dpop#1]
draft-ietf-oauth-signed-http-request also defines token_type pop.  Assuming that draft-ietf-oauth-signed-http-request stays dead, this isn't a problem.  But I wanted to call out the conflict so that we're aware of it.

I view this as a tracking issue - not a bug - and I don't propose any action to address it at this time.

**Comment by selfissued** [comment]
FYI, I deleted this from the draft `[ Maybe use different `token_type` value? ]` in my forthcoming pull request since it's preferable to track issues via the tracker than in the draft.

**Comment by webhamster** [comment]
I now use the new token type bearer+dpop.
