### ISSUE TITLE
Naming inconsistency - "pop" versus "dpop"

### ISSUE THREAD

**Issue by selfissued** [webhamster/draft-dpop#2]
The draft uses both the token_type identifier "pop" and the identifiers DPoP-Binding, dpop-binding+jwt, etc.  We should either use the string "pop" or "dpop" consistently in all our identifiers.

I'd advocate for simply "pop" - with the presumption that our draft eventually carries the day.

**Comment by webhamster** [comment]
Token type is now bearer+dpop, because it is a bearer token which needs dpop confirmation.
