### ISSUE TITLE
The contrstruct b64'...' is not legal JSON

### ISSUE THREAD

**Issue by selfissued** [webhamster/draft-dpop#3]
The document contains example values like b64'usWxHK2PmfnHKwXPS54m0kTcGJ90UiglWiGahtagnv8' - which are not legal JSON.  We need to replace these with base64url-encoded string values.

**Comment by selfissued** [comment]
Likewise, "kid" : h'11' is not legal JSON.

**Comment by webhamster** [comment]
Done.
