### ISSUE TITLE
Inclusion of dpop+jwk cnf value should be a MUST rather than SHOULD

### ISSUE THREAD

**Issue by selfissued** [webhamster/draft-dpop#7]
The draft currently says "Access tokens that are represented as JSON Web Tokens (JWT)[RFC7519] SHOULD contain information about the DPoP public key (in JWK format) in a member dpop+jwk of the cnf claim."

It seems to me that this SHOULD should be a MUST.  When would an implementation not want/need this?

**Comment by webhamster** [comment]
Done.
